### PR TITLE
Add credentials service methods for backend.

### PR DESCRIPTION
**Pull request by smarlowucf**
Credentials encrypted with encryption key and stored in separate files.

### CODE REVIEW

**Comment by schaefi** [comment]
So cryptography.fernet is our choice as it seems. Looks good for me but I think we should give Robert a chance to review too

**Comment by smarlowucf** [comment]
> So cryptography.fernet is our choice as it seems. Looks good for me but I think we should give Robert a chance to review too

Yeah, good to have agreement here. I'm no expert in choosing encryption methods. Cryptography seems to be the best python crypto library and Fernet is their recommended option for encrypting strings.

**Comment by smarlowucf** [comment]
Note: Depending on the decision here the file path generation should be moved to a separate method to prevent duplication and making changing the path structure easier.

```
path = os.path.join(
    self.credentials_directory, user, provider, account
)
```

**Comment by smarlowucf** [comment]
Updated per discussion. We will use the MultiFernet types and save keys in a file. This will enable the possibility for key rotation in the future.

**Comment by smarlowucf** [comment]
Opening a new request with base and credentials service methods .

**Pull request closed without merging**
