### PR TITLE
Add schema validator for job message.

### PR DESCRIPTION
**Pull request by smarlowucf**
- Requires jsonschema and strict-rfc3339 packages. strict-rfc3339 is used for validation the date-time format.
- Update the target_regions accounts attr to be a list of dictionaries with name and regions keys.

### CODE REVIEW

**Comment by smarlowucf** [comment]
Do we want to update the package conditions for OBS to be more explicit?

```
"conditions": [
      {"name": "cool_package", "constraints": [">=1.0.0", "<=2.0.0"]},
      {"image": "version"}
  ]
```

Or even more so:

```
"conditions": [
      {"name": "cool_package", "lower_bound": ">=1.0.0", "upper_bound": "<=2.0.0"},
      {"image": "version"}
  ]
```

**Comment by smarlowucf** [comment]
Assuming we want to validate the utctime format in the schema I will go ahead and package the python requirement https://github.com/danielrichman/strict-rfc3339.

**Comment by smarlowucf** [comment]
Added base validation method and updated requirements.

**Comment by schaefi** [comment]
Regarding the package constraints I like the last version you posted and opened an issue for it in #194

**Pull request merged**
