### PR TITLE
Decompress the Azure image for upload.

### PR DESCRIPTION
**Pull request by smarlowucf**
@schaefi @rjschwei This still needs update to unit tests but does this look okay? Using shutil to do a buffered decompress and copy?

All Azure images will need this done so I think this fits in the Azure upload class.

### CODE REVIEW

**Comment by schaefi** [comment]
Hmm, no I wouldn't do that. If we change the azure uploader to support compressed streams we should do it right from the beginning on. This means the following steps:

1. simply copy my ./utils/xz.py from the azurectl sources to mash
2. instead of page_blob_service.create_blob_from_path() use page_blob_service.create_blob_from_stream() and put the opening of the file into mash code

This will then automatically detect the file type open the stream appropriately, does chunk based decompression and the performance is ok

I can do that once we have sorted out all other blocking azure issues. Feel free top open an issue assigned to me, I'll jump on it as soon as I have a free slot

**Comment by smarlowucf** [comment]
The LZMAFile used as context manager provides a buffer stream which uses LZMADecompressor which decompresses data incrementally. This appears to be what `./utils/xz.py` does right? Why not use builtins?

> This will then automatically detect the file type open the stream appropriately

This doesn't hurt but will we ever get an image from OBS that isn't compressed and that we don't need to decompress to upload to Azure?

What about something like:

```
if self.system_image_file.rsplit('.', maxsplit=1)[1] == 'xz':
    f_type = lzma.LZMAFile
else:
    f_type = open

with f_type(self.system_image_file) as f:
    page_blob_service.create_blob_from_stream(
        self.container_name, self.cloud_image_name, f,
        max_connections=4
    )
```

**Comment by rjschwei** [comment]
We might have to support Stemcell uploads created by the CF pipeline and I am not certain we will get a compressed file out of that. So a detection is not necessarily a waste of time. Another expansion on the horizon would be to feed mash with a locally built image. However both of these cocepts apply universally and I do not necessarily want to implement or design for these at this point, YAGNI.

I am fine with using LZMA

**Comment by schaefi** [comment]
> I am fine with using LZMA

we are using LZMA. The question is if the implementation I did with 
lzma.LZMADecompressor can be completely replaced with lzma.LZMAFile

reading the docs I don't see where lzma.LZMAFile implements an incremental decompression
which allows me to specify the buffer size. Maybe I just overlooked something.

Of course if simple opening with lzma.LZMAFile does the reading in chunks as we
need it I would use this.

Please also take into account that the code I have used here has already proven to
work in the context of azure uploading during the time we used azurectl. I think just
making use of it will be the most easy approach.

While investigating all this I was also reading the azure sdk code and I see they have
implemented the zero page handling but I could not see that they have implemented the
retry of pages as we have it in azurectl. The constant timeout issues I have when uploading
go away with the retry page code we have in azurectl. This might be only because of my
bad connection but just to mention we had a lot in azurectl which made our upload life easier

**Comment by smarlowucf** [comment]
> reading the docs I don't see where lzma.LZMAFile implements an incremental decompression
> which allows me to specify the buffer size. Maybe I just overlooked something.

It's briefly mentioned for LZMADecompressor which the LZMAFile uses for reading, "which can be used to decompress data incrementally". But looking at the impl in cpython it ends up using a DecompressReader which is a buffer.

In testing this was the case.

> While investigating all this I was also reading the azure sdk code and I see they have
> implemented the zero page handling but I could not see that they have implemented the
> retry of pages as we have it in azurectl. The constant timeout issues I have when uploading
> go away with the retry page code we have in azurectl. This might be only because of my
> bad connection but just to mention we had a lot in azurectl which made our upload life easier

Not sure if it can handle retry on timeouts.

It's probably worth giving the different options a test since this is going to be the biggest bottleneck in the pipeline.

**Comment by smarlowucf** [comment]
create_blob_from_stream for pageBlob requires a count parameter which is the size of buffer to read. Given the size is unknown in our case I think we will need two steps. First decompress to local disk then create blob from file or stream.

**Comment by schaefi** [comment]
Ah now that you say it I remember why I wrote the page blob iterator using the update_page() method from the sdk directly. That also implements the mentioned page retry. See here:

* https://github.com/SUSE/azurectl/blob/master/azurectl/storage/page_blob.py

Are we open to re-use this code ? I think we should.

**Comment by rjschwei** [comment]
Yes, we should reuse the code from azurectl

**Comment by smarlowucf** [comment]
> Are we open to re-use this code ? I think we should.

Actually if Azure forces the images to be 30G and 512 aligned then all decompressed files would be the same size? Or is the 512 alignment the only hard rule?

Given the size of the files maybe it is worth having better fault tolerance with retry on error/timeouts which you have in Azurectl.

Ideally we would:

- Create blob directly from LZMA decompression stream and not require temp storage on disk.
- Don't send empty pages, which is covered with either route.
- Have ability to retry update of pages if timeout or errors occur.

So we could use the LZMAFile along with page_blob impl from azurectl to accomplish this?

**Comment by rjschwei** [comment]
The alignment is a requirement, the size is not. For testing purposes we could easily set up smaller images, the 30GB is mandated for release.

**Comment by smarlowucf** [comment]
> The alignment is a requirement, the size is not.

Okay. Good to use code from azurectl and LZMAFile if we can.

**Comment by schaefi** [comment]
I have updated #241 accordingly

**Comment by smarlowucf** [comment]
Closing: superseded by #241

**Pull request closed without merging**
