### PR TITLE
Move remove job config method to base class.

### PR DESCRIPTION
**Pull request by smarlowucf**

### CODE REVIEW

**Comment by smarlowucf** [comment]
Agree, name isn't the best...

**Comment by smarlowucf** [comment]
Looks like the dateutil plugin changed error format on latest update. Will fix in master and re-merge to open requests.

**Comment by smarlowucf** [comment]
Okay, fixed now. Maybe we should pin the test requirements to minor versions to prevent this type of breakage when packages update changes that aren't compatible?

`python-dateutil~=2.7`

To get patch updates but prevent breaking updates.

**Comment by schaefi** [comment]
This changes looks good to me :+1:

**Pull request merged**
